sudo: required

services:
  - docker

before_install:
  - docker build -t lcsfreund/react-test -f ./client/Dockerfile.dev ./client/

script:
  - docker run lcsfreund/react-test npm test -- --coverage

after_success:
  - docker build -t lcsfreund/multi-client ./client
  - docker build -t lcsfreund/multi-nginx ./nginx
  - docker build -t lcsfreund/multi-server ./server
  - docker build -t lcsfreund/multi-server ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin # Piping the password prevents it from showing up in logs

  - docker push lcsfreund/multi-client
  - docker push lcsfreund/multi-nginx
  - docker push lcsfreund/multi-server
  - docker push lcsfreund/multi-worker